ConnectContactBundle:
    resource: "@ConnectContactBundle/Resources/config/routing.yml"
    prefix:   /
    type: rest

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
